### PR TITLE
Add Heroku support

### PR DESCRIPTION
**Pull request by andrusha**
Hey, hat.jit.su lately wasn't very stable, so I decided to make my own deployment. Having this `Procfile` in repo will allow you to just push code to Heroku repo and the app will be ready to use.

### CODE REVIEW

**Comment by d48** [comment]
:+1:  the nodejitsu app was down. I like how I can have a clone of this running on heroku. By the way @andrusha, do you happen to have an instance on heroku running already I can reference?

**Comment by andrusha** [comment]
@d48 yeap, I have it deployed here topjitsu.herokuapp.com

**Comment by d48** [comment]
awesome, thanks @andrusha for the link. just noticed it's here too: http://hatjitsu.herokuapp.com/

**Comment by andrusha** [comment]
@d48 any plans on merging this?

**Comment by d48** [comment]
Hello, I actually don't have permissions. It would need to be someone like @richarcher , but in general you can just clone this repo and modify it yourself as needed

**Pull request merged**
